<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FlashCap" />
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="OpenCvSharp5" />
		<PackageReference Include="OpenCvSharp5.runtime.win" />
		<PackageReference Include="OpenCvSharp5.official.runtime.linux-x64" />
		<PackageReference Include="OpenCvSharp5.runtime.osx.arm64" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EzTesseract\EzTesseract.csproj" />
	</ItemGroup>

</Project>
