<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FlashCap" />
						<PackageReference Include="System.Drawing.Common" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EzCv\EzCv.csproj" />
		<ProjectReference Include="..\EzTesseract\EzTesseract.csproj" />
	</ItemGroup>

</Project>
