namespace EasyCon2.Avalonia.Core.Input;

/// <summary>
/// Avalonia <see cref="global::Avalonia.Input.Key"/> 与 SDL 扫描码之间的映射，
/// 以及扫描码到展示名称的转换。为 UI 与虚拟手柄叠加层共用。
/// </summary>
public static class SdlScancodeMap
{
    /// <summary>按下即清除绑定 —— 这类按键不参与映射捕获。</summary>
    public static bool IsClearKey(global::Avalonia.Input.Key key)
    {
        return key is global::Avalonia.Input.Key.Escape or global::Avalonia.Input.Key.Back;
    }

    /// <summary>
    /// 系统保留键 —— 不允许绑定。
    /// 理由：① 徽标键/菜单键被操作系统截获，无法可靠捕获；
    /// ② 打印屏幕/Pause 由系统占用；③ 锁定类按键会改变键盘全局状态。
    /// </summary>
    public static bool IsReservedKey(global::Avalonia.Input.Key key)
    {
        return key is global::Avalonia.Input.Key.LWin
            or global::Avalonia.Input.Key.RWin
            or global::Avalonia.Input.Key.Apps
            or global::Avalonia.Input.Key.PrintScreen
            or global::Avalonia.Input.Key.Pause
            or global::Avalonia.Input.Key.CapsLock
            or global::Avalonia.Input.Key.NumLock
            or global::Avalonia.Input.Key.Scroll;
    }

    /// <summary>Avalonia Key → SDL_Scancode；不支持的按键返回 -1。</summary>
    public static int FromAvaloniaKey(global::Avalonia.Input.Key key)
    {
        return key switch
        {
            global::Avalonia.Input.Key.A => 4,
            global::Avalonia.Input.Key.B => 5,
            global::Avalonia.Input.Key.C => 6,
            global::Avalonia.Input.Key.D => 7,
            global::Avalonia.Input.Key.E => 8,
            global::Avalonia.Input.Key.F => 9,
            global::Avalonia.Input.Key.G => 10,
            global::Avalonia.Input.Key.H => 11,
            global::Avalonia.Input.Key.I => 12,
            global::Avalonia.Input.Key.J => 13,
            global::Avalonia.Input.Key.K => 14,
            global::Avalonia.Input.Key.L => 15,
            global::Avalonia.Input.Key.M => 16,
            global::Avalonia.Input.Key.N => 17,
            global::Avalonia.Input.Key.O => 18,
            global::Avalonia.Input.Key.P => 19,
            global::Avalonia.Input.Key.Q => 20,
            global::Avalonia.Input.Key.R => 21,
            global::Avalonia.Input.Key.S => 22,
            global::Avalonia.Input.Key.T => 23,
            global::Avalonia.Input.Key.U => 24,
            global::Avalonia.Input.Key.V => 25,
            global::Avalonia.Input.Key.W => 26,
            global::Avalonia.Input.Key.X => 27,
            global::Avalonia.Input.Key.Y => 28,
            global::Avalonia.Input.Key.Z => 29,
            global::Avalonia.Input.Key.D1 => 30,
            global::Avalonia.Input.Key.D2 => 31,
            global::Avalonia.Input.Key.D3 => 32,
            global::Avalonia.Input.Key.D4 => 33,
            global::Avalonia.Input.Key.D5 => 34,
            global::Avalonia.Input.Key.D6 => 35,
            global::Avalonia.Input.Key.D7 => 36,
            global::Avalonia.Input.Key.D8 => 37,
            global::Avalonia.Input.Key.D9 => 38,
            global::Avalonia.Input.Key.D0 => 39,
            global::Avalonia.Input.Key.Return => 40,
            global::Avalonia.Input.Key.Escape => 41,
            global::Avalonia.Input.Key.Back => 42,
            global::Avalonia.Input.Key.Tab => 43,
            global::Avalonia.Input.Key.Space => 44,
            global::Avalonia.Input.Key.OemMinus => 45,
            global::Avalonia.Input.Key.OemPlus => 46,
            global::Avalonia.Input.Key.OemOpenBrackets => 47,
            global::Avalonia.Input.Key.OemCloseBrackets => 48,
            global::Avalonia.Input.Key.OemPipe => 49,
            global::Avalonia.Input.Key.OemTilde => 50,
            global::Avalonia.Input.Key.OemSemicolon => 51,
            global::Avalonia.Input.Key.OemQuotes => 52,
            global::Avalonia.Input.Key.OemComma => 54,
            global::Avalonia.Input.Key.OemPeriod => 55,
            global::Avalonia.Input.Key.OemQuestion => 56,
            global::Avalonia.Input.Key.CapsLock => 57,
            global::Avalonia.Input.Key.F1 => 58,
            global::Avalonia.Input.Key.F2 => 59,
            global::Avalonia.Input.Key.F3 => 60,
            global::Avalonia.Input.Key.F4 => 61,
            global::Avalonia.Input.Key.F5 => 62,
            global::Avalonia.Input.Key.F6 => 63,
            global::Avalonia.Input.Key.F7 => 64,
            global::Avalonia.Input.Key.F8 => 65,
            global::Avalonia.Input.Key.F9 => 66,
            global::Avalonia.Input.Key.F10 => 67,
            global::Avalonia.Input.Key.F11 => 68,
            global::Avalonia.Input.Key.F12 => 69,
            global::Avalonia.Input.Key.F13 => 104,
            global::Avalonia.Input.Key.F14 => 105,
            global::Avalonia.Input.Key.F15 => 106,
            global::Avalonia.Input.Key.F16 => 107,
            global::Avalonia.Input.Key.F17 => 108,
            global::Avalonia.Input.Key.F18 => 109,
            global::Avalonia.Input.Key.F19 => 110,
            global::Avalonia.Input.Key.F20 => 111,
            global::Avalonia.Input.Key.F21 => 112,
            global::Avalonia.Input.Key.F22 => 113,
            global::Avalonia.Input.Key.F23 => 114,
            global::Avalonia.Input.Key.F24 => 115,
            global::Avalonia.Input.Key.PrintScreen => 70,
            global::Avalonia.Input.Key.Scroll => 71,
            global::Avalonia.Input.Key.Pause => 72,
            global::Avalonia.Input.Key.Insert => 73,
            global::Avalonia.Input.Key.Home => 74,
            global::Avalonia.Input.Key.PageUp => 75,
            global::Avalonia.Input.Key.Delete => 76,
            global::Avalonia.Input.Key.End => 77,
            global::Avalonia.Input.Key.PageDown => 78,
            global::Avalonia.Input.Key.Right => 79,
            global::Avalonia.Input.Key.Left => 80,
            global::Avalonia.Input.Key.Down => 81,
            global::Avalonia.Input.Key.Up => 82,
            global::Avalonia.Input.Key.NumLock => 83,
            global::Avalonia.Input.Key.Divide => 84,
            global::Avalonia.Input.Key.Multiply => 85,
            global::Avalonia.Input.Key.Subtract => 86,
            global::Avalonia.Input.Key.Add => 87,
            global::Avalonia.Input.Key.NumPad1 => 89,
            global::Avalonia.Input.Key.NumPad2 => 90,
            global::Avalonia.Input.Key.NumPad3 => 91,
            global::Avalonia.Input.Key.NumPad4 => 92,
            global::Avalonia.Input.Key.NumPad5 => 93,
            global::Avalonia.Input.Key.NumPad6 => 94,
            global::Avalonia.Input.Key.NumPad7 => 95,
            global::Avalonia.Input.Key.NumPad8 => 96,
            global::Avalonia.Input.Key.NumPad9 => 97,
            global::Avalonia.Input.Key.NumPad0 => 98,
            global::Avalonia.Input.Key.Decimal => 99,
            global::Avalonia.Input.Key.OemBackslash => 100,
            global::Avalonia.Input.Key.LeftCtrl => 224,
            global::Avalonia.Input.Key.LeftShift => 225,
            global::Avalonia.Input.Key.LeftAlt => 226,
            global::Avalonia.Input.Key.LWin => 227,
            global::Avalonia.Input.Key.RightCtrl => 228,
            global::Avalonia.Input.Key.RightShift => 229,
            global::Avalonia.Input.Key.RightAlt => 230,
            global::Avalonia.Input.Key.RWin => 231,
            _ => -1,
        };
    }

    /// <summary>SDL_Scancode → 显示名称。</summary>
    public static string ToDisplayName(int sc)
    {
        if (sc == 0) return "—";
        return sc switch
        {
            4 => "A",
            5 => "B",
            6 => "C",
            7 => "D",
            8 => "E",
            9 => "F",
            10 => "G",
            11 => "H",
            12 => "I",
            13 => "J",
            14 => "K",
            15 => "L",
            16 => "M",
            17 => "N",
            18 => "O",
            19 => "P",
            20 => "Q",
            21 => "R",
            22 => "S",
            23 => "T",
            24 => "U",
            25 => "V",
            26 => "W",
            27 => "X",
            28 => "Y",
            29 => "Z",
            30 => "1",
            31 => "2",
            32 => "3",
            33 => "4",
            34 => "5",
            35 => "6",
            36 => "7",
            37 => "8",
            38 => "9",
            39 => "0",
            40 => "Enter",
            41 => "Esc",
            42 => "Back",
            43 => "Tab",
            44 => "Space",
            45 => "-",
            46 => "=",
            47 => "[",
            48 => "]",
            49 => "\\",
            50 => "`",
            51 => ";",
            52 => "'",
            54 => ",",
            55 => ".",
            56 => "/",
            57 => "Caps",
            58 => "F1",
            59 => "F2",
            60 => "F3",
            61 => "F4",
            62 => "F5",
            63 => "F6",
            64 => "F7",
            65 => "F8",
            66 => "F9",
            67 => "F10",
            68 => "F11",
            69 => "F12",
            104 => "F13",
            105 => "F14",
            106 => "F15",
            107 => "F16",
            108 => "F17",
            109 => "F18",
            110 => "F19",
            111 => "F20",
            112 => "F21",
            113 => "F22",
            114 => "F23",
            115 => "F24",
            70 => "PrtSc",
            71 => "ScrLk",
            72 => "Pause",
            73 => "Ins",
            74 => "Home",
            75 => "PgUp",
            76 => "Del",
            77 => "End",
            78 => "PgDn",
            79 => "→",
            80 => "←",
            81 => "↓",
            82 => "↑",
            83 => "NumLk",
            84 => "N/",
            85 => "N*",
            86 => "N-",
            87 => "N+",
            88 => "NEnter",
            89 => "N1",
            90 => "N2",
            91 => "N3",
            92 => "N4",
            93 => "N5",
            94 => "N6",
            95 => "N7",
            96 => "N8",
            97 => "N9",
            98 => "N0",
            99 => "N.",
            100 => "\\",
            224 => "LCtrl",
            225 => "LShift",
            226 => "LAlt",
            227 => "LWin",
            228 => "RCtrl",
            229 => "RShift",
            230 => "RAlt",
            231 => "RWin",
            _ => $"SC{sc}",
        };
    }
}