//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCon2.UI.Common.Properties
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyCon2.UI.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture { get; set; }

        public static byte[] Amiibo
        {
            get
            {
                object obj = ResourceManager.GetObject("Amiibo", Culture);
                return ((byte[])(obj));
            }
        }

        public static string capturedoc
        {
            get
            {
                return ResourceManager.GetString("capturedoc", Culture);
            }
        }

        public static byte[] CaptureVideo
        {
            get
            {
                object obj = ResourceManager.GetObject("CaptureVideo", Culture);
                return ((byte[])(obj));
            }
        }

        public static byte[] clrlog
        {
            get
            {
                object obj = ResourceManager.GetObject("clrlog", Culture);
                return ((byte[])(obj));
            }
        }

        public static byte[] ecp
        {
            get
            {
                object obj = ResourceManager.GetObject("ecp", Culture);
                return ((byte[])(obj));
            }
        }

        public static byte[] lua
        {
            get
            {
                object obj = ResourceManager.GetObject("lua", Culture);
                return ((byte[])(obj));
            }
        }

        public static byte[] Python_Mode
        {
            get
            {
                object obj = ResourceManager.GetObject("Python-Mode", Culture);
                return ((byte[])(obj));
            }
        }

        public static string scriptdoc
        {
            get
            {
                return ResourceManager.GetString("scriptdoc", Culture);
            }
        }

        public static byte[] tmp
        {
            get
            {
                object obj = ResourceManager.GetObject("tmp", Culture);
                return ((byte[])(obj));
            }
        }
    }
}
